/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ApexOptions } from "apexcharts";
export { ApexOptions } from "apexcharts";
export namespace Components {
    interface ApexChart {
        /**
          * Chart height
         */
        "height"?: string | number;
        /**
          * Chart configuration options
         */
        "options"?: ApexOptions;
        /**
          * Destroy and recreate the chart
         */
        "refresh": () => Promise<void>;
        /**
          * Chart series data
         */
        "series"?: ApexOptions['series'];
        /**
          * Chart type
         */
        "type"?: ChartType;
        /**
          * Update chart configuration
         */
        "updateOptions": (newOptions: ApexOptions, redrawPaths?: boolean, animate?: boolean) => Promise<void>;
        /**
          * Update chart series
         */
        "updateSeries": (newSeries: ApexOptions["series"], animate?: boolean) => Promise<void>;
        /**
          * Chart width
         */
        "width"?: string | number;
    }
    interface ApexChartElement {
        "getData": () => Promise<any>;
    }
}
declare global {
    interface HTMLApexChartElement extends Components.ApexChart, HTMLStencilElement {
    }
    var HTMLApexChartElement: {
        prototype: HTMLApexChartElement;
        new (): HTMLApexChartElement;
    };
    interface HTMLApexChartElementElement extends Components.ApexChartElement, HTMLStencilElement {
    }
    var HTMLApexChartElementElement: {
        prototype: HTMLApexChartElementElement;
        new (): HTMLApexChartElementElement;
    };
    interface HTMLElementTagNameMap {
        "apex-chart": HTMLApexChartElement;
        "apex-chart-element": HTMLApexChartElementElement;
    }
}
declare namespace LocalJSX {
    interface ApexChart {
        /**
          * Chart height
         */
        "height"?: string | number;
        /**
          * Chart configuration options
         */
        "options"?: ApexOptions;
        /**
          * Chart series data
         */
        "series"?: ApexOptions['series'];
        /**
          * Chart type
         */
        "type"?: ChartType;
        /**
          * Chart width
         */
        "width"?: string | number;
    }
    interface ApexChartElement {
    }
    interface IntrinsicElements {
        "apex-chart": ApexChart;
        "apex-chart-element": ApexChartElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "apex-chart": LocalJSX.ApexChart & JSXBase.HTMLAttributes<HTMLApexChartElement>;
            "apex-chart-element": LocalJSX.ApexChartElement & JSXBase.HTMLAttributes<HTMLApexChartElementElement>;
        }
    }
}
